# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Avoid flagging book highlighting and section marking
Layout/LeadingCommentSpace:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
